source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Inlinit_Example', :exclusive => true do
  pod "Inlinit", :path => "../"
end

target 'Inlinit_Tests', :exclusive => true do
  pod "Inlinit", :path => "../"

  
end
